# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FCTR.be - eenvoudige vereenvoudigde boekhouding
email: peter.backx@fctr.be
description: eenvoudige vereenvoudigde boekhouding
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fctr.be" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

permalink: /:year/:month/:title/

defaults:
  -
    scope:
      path: "kennisbank"
      type: "posts"
    values:
      permalink: "/kennisbank/:title/"
